language: node_js
node_js: 
  - "10"
# before_script:
#   - npm install -g firebase-tools
script:
  - echo "deploying ..."

install:
  - npm install -g firebase-tools

after_success:
  - firebase deploy --only hosting --token $FIREBASE_TOKEN